# Generated by Django 6.0.7 on 2026-08-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('BUYER', 'Buyer')], default='BUYER', max_length=20),
        ),
    ]
