# Generated by Django 6.0.7 on 2026-08-03 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(default="bi-egg-fried", max_length=50)),
                ("image", models.ImageField(upload_to="categories/")),
                ("badge", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("item_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("discount_percentage", models.IntegerField(default=0)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Per Kg"),
                            ("dozen", "Per Dozen"),
                            ("bottle", "Per Bottle"),
                            ("liter", "Per Liter"),
                            ("quintal", "Per Quintal"),
                        ],
                        default="kg",
                        max_length=20,
                    ),
                ),
                ("unit_options", models.JSONField(default=list)),
                ("stock", models.IntegerField(default=100)),
                ("is_organic", models.BooleanField(default=True)),
                ("is_direct_from_farmer", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_today_deal", models.BooleanField(default=False)),
                (
                    "deal_timer_hours",
                    models.IntegerField(blank=True, default=12, null=True),
                ),
                (
                    "harvest_date",
                    models.CharField(default="Today (Morning 5:30 AM)", max_length=100),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("gallery", models.JSONField(default=list)),
                ("description", models.TextField()),
                ("specifications", models.JSONField(default=dict)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("rating_count", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="productsapp.category",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=5)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="productsapp.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
