export const topProducts = [
  {
    id: 1,
    name: "Organic Mango",
    farmer: "Nature Farms",
    price: 180,
    oldPrice: 220,
    rating: 5.0,
    stock: "Best Seller",
    image: "🥭",
  },
  {
    id: 2,
    name: "Fresh Apple",
    farmer: "Hill Farm",
    price: 150,
    oldPrice: 180,
    rating: 4.9,
    stock: "Popular",
    image: "🍎",
  },
  {
    id: 3,
    name: "Organic Banana",
    farmer: "Green Farm",
    price: 60,
    oldPrice: 75,
    rating: 4.8,
    stock: "In Stock",
    image: "🍌",
  },
  {
    id: 4,
    name: "Fresh Grapes",
    farmer: "Organic Valley",
    price: 90,
    oldPrice: 120,
    rating: 4.9,
    stock: "Top Rated",
    image: "🍇",
  },
];